import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database.
#
# When DATABASE_URL is set, dev points at that database instead of the local
# docker Postgres — e.g. to reset/seed the Neon prod DB from a local BEAM.
# IMPORTANT: use Neon's *direct* endpoint, not the `-pooler` (PgBouncer) one.
# Transaction pooling can't hold a LISTEN, which silently kills the EventStore's
# LISTEN/NOTIFY projector delivery: events append fine but projectors never ack,
# so `consistency: :strong` dispatches hang and time out. Migrations still pass on
# the pooler, so it looks healthy right up until you seed.
# CAUTION: this makes *every* dev mix command (incl. the destructive `mix reset`)
# operate on that database, so pass it inline rather than exporting it.
database_url = System.get_env("DATABASE_URL")

# Local docker Postgres defaults (used when DATABASE_URL is unset).
local_db = [username: "postgres", password: "postgres", hostname: "localhost"]

# When a URL is given, mirror config/runtime.exs's prod handling: TLS on (Neon
# requires it), and for the EventStore strip the query string, since its URL
# parser rejects Neon's `sslmode` param. The EventStore shares this database in
# its own `event_store` schema, so one DATABASE_URL provisions both.
repo_db =
  if database_url,
    do: [url: database_url, ssl: true],
    else: local_db ++ [database: "latchkey_dev"]

event_store_db =
  if database_url,
    do: [url: URI.to_string(%{URI.parse(database_url) | query: nil}), ssl: true],
    else: local_db ++ [database: "latchkey_dev", port: 5432]

config :latchkey,
       Latchkey.Repo,
       [stacktrace: true, show_sensitive_data_on_connection_error: true, pool_size: 10] ++ repo_db

# Commanded EventStore — shares the Ecto/Ash database above, isolated in its own
# `event_store` schema (created by `mix event_store.init`, wired into setup/test).
config :latchkey, Latchkey.EventStore, [schema: "event_store", pool_size: 5] ++ event_store_db

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :latchkey, LatchkeyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "H3OQr9MadObs8p3zA6ktU2WWGD6aiBLboSNi9kumjpr4XIBUYdXTKc4Ii7WoSjqM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:latchkey, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:latchkey, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :latchkey, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
