defmodule Latchkey.Repo.Migrations.RequireDirectoryIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sim_tenancy_directory) do
      modify :property_address, :text, null: false
      modify :tenant_name, :text, null: false
    end
  end

  def down do
    alter table(:sim_tenancy_directory) do
      modify :tenant_name, :text, null: true
      modify :property_address, :text, null: true
    end
  end
end
