defmodule Latchkey.Repo.Migrations.PmArrearsReadModel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pm_tenancy_arrears, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenancy_id, :text, null: false
      add :balance_cents, :bigint
      add :days_behind, :bigint
      add :oldest_unpaid_due_date, :date
      add :as_of, :date
    end

    create unique_index(:pm_tenancy_arrears, [:tenancy_id],
             name: "pm_tenancy_arrears_tenancy_index"
           )
  end

  def down do
    drop_if_exists unique_index(:pm_tenancy_arrears, [:tenancy_id],
                     name: "pm_tenancy_arrears_tenancy_index"
                   )

    drop table(:pm_tenancy_arrears)
  end
end
