defmodule Latchkey.Repo.Migrations.SpikeAshEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:spike_ash_tenancy_arrears, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenancy_id, :text, null: false
      add :balance_cents, :bigint
      add :days_behind, :bigint
      add :oldest_unpaid_due_date, :date
      add :as_of, :date
    end

    create unique_index(:spike_ash_tenancy_arrears, [:tenancy_id],
             name: "spike_ash_tenancy_arrears_tenancy_index"
           )

    create table(:spike_ash_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stream_id, :text, null: false
      add :sequence, :bigint, null: false
      add :type, :text, null: false
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:spike_ash_events, [:stream_id, :sequence],
             name: "spike_ash_events_stream_sequence_index"
           )
  end

  def down do
    drop_if_exists unique_index(:spike_ash_events, [:stream_id, :sequence],
                     name: "spike_ash_events_stream_sequence_index"
                   )

    drop table(:spike_ash_events)

    drop_if_exists unique_index(:spike_ash_tenancy_arrears, [:tenancy_id],
                     name: "spike_ash_tenancy_arrears_tenancy_index"
                   )

    drop table(:spike_ash_tenancy_arrears)
  end
end
