defmodule Latchkey.Repo.Migrations.AddArrearsStatusAndFinalBalance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pm_tenancy_arrears) do
      add :status, :text
      add :final_balance_cents, :bigint
    end
  end

  def down do
    alter table(:pm_tenancy_arrears) do
      remove :final_balance_cents
      remove :status
    end
  end
end
