defmodule Latchkey.Repo.Migrations.DropArrearsDaysBehindAsOf do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pm_tenancy_arrears) do
      remove :as_of
      remove :days_behind
    end
  end

  def down do
    alter table(:pm_tenancy_arrears) do
      add :days_behind, :bigint
      add :as_of, :date
    end
  end
end
