defmodule Latchkey.Repo.Migrations.CreateSimDirectory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sim_tenancy_directory, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tenancy_id, :text, null: false
      add :tenant_name, :text
      add :property_address, :text
    end

    create unique_index(:sim_tenancy_directory, [:tenancy_id],
             name: "sim_tenancy_directory_tenancy_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sim_tenancy_directory, [:tenancy_id],
                     name: "sim_tenancy_directory_tenancy_index"
                   )

    drop table(:sim_tenancy_directory)
  end
end
